@file:OptIn(org.jetbrains.kotlin.compiler.plugin.ExperimentalCompilerApi::class)

package com.nickanderssohn.declarativejooq.codegen

import com.tschuchort.compiletesting.KotlinCompilation
import com.tschuchort.compiletesting.SourceFile
import org.h2.jdbcx.JdbcDataSource
import org.jooq.DSLContext
import org.jooq.SQLDialect
import org.jooq.impl.DSL
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import java.io.File

class CodeGeneratorTest {

    private val classDir = File("../dsl-runtime/build/classes/kotlin/test")
    private val outputPackage = "com.nickanderssohn.generated"
    private lateinit var generatedSources: List<Pair<String, String>>

    @BeforeEach
    fun setUp() {
        assertTrue(classDir.exists(), "Run ./gradlew :dsl-runtime:testClasses first — missing: ${classDir.absolutePath}")
        generatedSources = CodeGenerator().generateSource(classDir, outputPackage, "com.nickanderssohn.declarativejooq")
        assertTrue(generatedSources.isNotEmpty(), "CodeGenerator produced no source files")
    }

    /**
     * Creates an H2 in-memory DSLContext with the organization + app_user schema.
     * Uses a per-call unique DB name to keep each test isolated.
     */
    private fun freshContext(): DSLContext {
        // Use a unique DB name per call to avoid cross-test contamination
        val dbName = "test_${System.nanoTime()}"
        val url = "jdbc:h2:mem:$dbName;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE"
        val ds = JdbcDataSource().apply { setURL(url) }
        val ctx = DSL.using(ds, SQLDialect.H2)
        ctx.execute(
            """
            CREATE TABLE IF NOT EXISTS organization (
                id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255) NOT NULL
            )
            """.trimIndent()
        )
        ctx.execute(
            """
            CREATE TABLE IF NOT EXISTS app_user (
                id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name            VARCHAR(255) NOT NULL,
                email           VARCHAR(255) NOT NULL,
                organization_id BIGINT NOT NULL REFERENCES organization(id)
            )
            """.trimIndent()
        )
        ctx.execute(
            """
            CREATE TABLE IF NOT EXISTS category (
                id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name      VARCHAR(255) NOT NULL,
                parent_id BIGINT REFERENCES category(id)
            )
            """.trimIndent()
        )
        ctx.execute(
            """
            CREATE TABLE IF NOT EXISTS task (
                id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title      VARCHAR(255) NOT NULL,
                created_by BIGINT NOT NULL REFERENCES app_user(id),
                updated_by BIGINT REFERENCES app_user(id)
            )
            """.trimIndent()
        )
        return ctx
    }

    private fun compile(extraSources: List<SourceFile> = emptyList()): KotlinCompilation.Result {
        val sources = generatedSources.map { (name, code) -> SourceFile.kotlin(name, code) } + extraSources
        return KotlinCompilation().apply {
            this.sources = sources
            inheritClassPath = true
            messageOutputStream = System.out
            // kotlin-compile-testing 1.6.0 bundles Kotlin 1.9.x compiler but our project uses Kotlin 2.x.
            // -Xskip-metadata-version-check allows the 1.9.x compiler to consume 2.x-compiled classes.
            kotlincArguments = listOf("-Xskip-metadata-version-check")
            // The generated code references dsl-runtime TEST classes (AppUserRecord, AppUserTable, etc.)
            // which live in the test classes dir, not in dsl-runtime.jar (main sources only).
            // Add the test classes dir explicitly so the compiler can resolve them.
            classpaths = classpaths + listOf(classDir)
        }.compile()
    }

    // -----------------------------------------------------------------------
    // Test 1: Generated code compiles
    // -----------------------------------------------------------------------

    @Test
    fun generatedCodeCompiles() {
        val result = compile()
        if (result.exitCode != KotlinCompilation.ExitCode.OK) {
            println("=== Compilation messages ===")
            println(result.messages)
            println("=== Generated sources ===")
            generatedSources.forEach { (name, code) ->
                println("--- $name ---")
                println(code)
            }
        }
        assertEquals(KotlinCompilation.ExitCode.OK, result.exitCode, "Generated code should compile successfully")
    }

    // -----------------------------------------------------------------------
    // Test 2: Generated builder classes have typed properties
    // -----------------------------------------------------------------------

    @Test
    fun generatedBuilderHasTypedProperties() {
        val result = compile()
        assertEquals(KotlinCompilation.ExitCode.OK, result.exitCode, "Compilation failed:\n${result.messages}")

        // OrganizationBuilder should have a 'name' property (Kotlin var compiles to getter+setter)
        val orgBuilderClass = result.classLoader.loadClass("$outputPackage.OrganizationBuilder")
        assertNotNull(orgBuilderClass, "OrganizationBuilder class not found")
        val orgNameGetter = orgBuilderClass.methods.firstOrNull { it.name == "getName" }
        val orgNameSetter = orgBuilderClass.methods.firstOrNull { it.name == "setName" }
        assertNotNull(orgNameGetter, "OrganizationBuilder should have getName() method")
        assertNotNull(orgNameSetter, "OrganizationBuilder should have setName() method")

        // AppUserBuilder should have 'name' and 'email' properties
        val appUserBuilderClass = result.classLoader.loadClass("$outputPackage.AppUserBuilder")
        assertNotNull(appUserBuilderClass, "AppUserBuilder class not found")
        val userNameGetter = appUserBuilderClass.methods.firstOrNull { it.name == "getName" }
        val emailGetter = appUserBuilderClass.methods.firstOrNull { it.name == "getEmail" }
        assertNotNull(userNameGetter, "AppUserBuilder should have getName() method")
        assertNotNull(emailGetter, "AppUserBuilder should have getEmail() method")
    }

    // -----------------------------------------------------------------------
    // Shared harness source — compiled alongside generated sources so that
    // everything runs in the same KotlinCompilation classloader.
    // Reflection is only used to cross the parent/child CL boundary at test invocation.
    // -----------------------------------------------------------------------

    private fun testHarnessSource(): SourceFile = SourceFile.kotlin(
        "TestHarness.kt",
        """
        package com.nickanderssohn.generated

        import com.nickanderssohn.declarativejooq.DslResult
        import com.nickanderssohn.declarativejooq.execute
        import org.jooq.DSLContext

        object TestHarness {
            /**
             * Inserts one organization + one app_user via generated builders.
             * Returns the raw DslResult (class loaded by parent CL — safe to cast in test).
             * Note: builder function is named after child table (organization_id matches parent -> appUser)
             */
            fun run(ctx: DSLContext): DslResult {
                return execute(ctx) {
                    organization {
                        name = "Acme"
                        appUser {
                            name = "Alice"
                            email = "alice@acme.com"
                        }
                    }
                }
            }

            /**
             * Runs as above, then wraps result in GeneratedDslResult.
             * Returned as Any so the calling test can access it via reflection.
             */
            fun runWithTypedResult(ctx: DSLContext): Any {
                val result = execute(ctx) {
                    organization {
                        name = "Acme"
                    }
                }
                return GeneratedDslResult(result)
            }
        }
        """.trimIndent()
    )

    // -----------------------------------------------------------------------
    // Test 3: Generated code executes against database
    // -----------------------------------------------------------------------

    @Test
    fun generatedCodeExecutesAgainstDatabase() {
        val result = compile(listOf(testHarnessSource()))
        assertEquals(KotlinCompilation.ExitCode.OK, result.exitCode, "Compilation failed:\n${result.messages}")

        val ctx = freshContext()
        val harnessClass = result.classLoader.loadClass("$outputPackage.TestHarness")
        val harnessInstance = harnessClass.getField("INSTANCE").get(null)
        val runMethod = harnessClass.getMethod("run", DSLContext::class.java)
        runMethod.invoke(harnessInstance, ctx)

        // Verify records were inserted
        val orgCount = ctx.selectCount().from(DSL.table("organization")).fetchOne(0, Int::class.java)!!
        val userCount = ctx.selectCount().from(DSL.table("app_user")).fetchOne(0, Int::class.java)!!
        assertEquals(1, orgCount, "Expected 1 organization record")
        assertEquals(1, userCount, "Expected 1 app_user record")
    }

    // -----------------------------------------------------------------------
    // Test 4: FK resolution works
    // -----------------------------------------------------------------------

    @Test
    fun fkResolutionWorks() {
        val result = compile(listOf(testHarnessSource()))
        assertEquals(KotlinCompilation.ExitCode.OK, result.exitCode, "Compilation failed:\n${result.messages}")

        val ctx = freshContext()
        val harnessClass = result.classLoader.loadClass("$outputPackage.TestHarness")
        val harnessInstance = harnessClass.getField("INSTANCE").get(null)
        val runMethod = harnessClass.getMethod("run", DSLContext::class.java)
        runMethod.invoke(harnessInstance, ctx)

        // Query and verify FK linkage
        val orgId = ctx
            .select(DSL.field("id"))
            .from(DSL.table("organization"))
            .fetchOne()
            ?.get(DSL.field("id"))

        val orgIdFk = ctx
            .select(DSL.field("organization_id"))
            .from(DSL.table("app_user"))
            .fetchOne()
            ?.get(DSL.field("organization_id"))

        assertNotNull(orgId, "Expected one organization row")
        assertNotNull(orgIdFk, "Expected one app_user row")
        assertEquals(orgId, orgIdFk, "app_user.organization_id should match organization.id")
    }

    // -----------------------------------------------------------------------
    // Edge case harness — compiled alongside generated sources for edge case tests
    // -----------------------------------------------------------------------

    private fun edgeCaseHarnessSource(): SourceFile = SourceFile.kotlin(
        "EdgeCaseHarness.kt",
        """
        package com.nickanderssohn.generated

        import com.nickanderssohn.declarativejooq.DslResult
        import com.nickanderssohn.declarativejooq.execute
        import org.jooq.DSLContext

        object EdgeCaseHarness {
            /**
             * Self-referential insert: Electronics -> Phones -> Smartphones
             */
            fun runSelfRef(ctx: DSLContext): DslResult {
                return execute(ctx) {
                    category {
                        name = "Electronics"
                        category {
                            name = "Phones"
                            category {
                                name = "Smartphones"
                            }
                        }
                    }
                }
            }

            /**
             * Multi-FK insert: AppUser nested under createdBy (FK from task.created_by -> app_user)
             */
            fun runMultiFk(ctx: DSLContext): DslResult {
                return execute(ctx) {
                    organization {
                        name = "Acme"
                        appUser {
                            name = "Alice"
                            email = "alice@acme.com"
                            createdBy {
                                title = "Created Task"
                            }
                        }
                    }
                }
            }
        }
        """.trimIndent()
    )

    // -----------------------------------------------------------------------
    // Test 6: Self-referential FK inserts with correct parent_id chain
    // -----------------------------------------------------------------------

    @Test
    fun selfReferentialFkInserts() {
        val result = compile(listOf(edgeCaseHarnessSource()))
        assertEquals(KotlinCompilation.ExitCode.OK, result.exitCode, "Compilation failed:\n${result.messages}")

        val ctx = freshContext()
        val harnessClass = result.classLoader.loadClass("$outputPackage.EdgeCaseHarness")
        val harnessInstance = harnessClass.getField("INSTANCE").get(null)
        val runMethod = harnessClass.getMethod("runSelfRef", DSLContext::class.java)
        runMethod.invoke(harnessInstance, ctx)

        // Verify 3 category rows were inserted
        val count = ctx.selectCount().from(DSL.table("category")).fetchOne(0, Int::class.java)!!
        assertEquals(3, count, "Expected 3 category rows")

        // Query all categories with their parent_id values
        val rows = ctx.select(DSL.field("name"), DSL.field("parent_id"))
            .from(DSL.table("category"))
            .fetch()

        val byName = rows.associateBy(
            { it.get(DSL.field("name")) as String },
            { it.get(DSL.field("parent_id")) }
        )

        assertNull(byName["Electronics"], "Electronics should have NULL parent_id")
        assertNotNull(byName["Phones"], "Phones should have non-null parent_id")
        assertNotNull(byName["Smartphones"], "Smartphones should have non-null parent_id")

        // Verify the chain: Phones.parent_id = Electronics.id, Smartphones.parent_id = Phones.id
        val electronicsId = ctx.select(DSL.field("id"))
            .from(DSL.table("category"))
            .where(DSL.field("name").eq("Electronics"))
            .fetchOne()?.get(DSL.field("id"))
        val phonesId = ctx.select(DSL.field("id"))
            .from(DSL.table("category"))
            .where(DSL.field("name").eq("Phones"))
            .fetchOne()?.get(DSL.field("id"))

        assertEquals(electronicsId, byName["Phones"], "Phones.parent_id should equal Electronics.id")
        assertEquals(phonesId, byName["Smartphones"], "Smartphones.parent_id should equal Phones.id")
    }

    // -----------------------------------------------------------------------
    // Test 7: Multiple FKs to same table produce distinct named builder functions
    // -----------------------------------------------------------------------

    @Test
    fun multipleFkNaming() {
        val result = compile()
        assertEquals(KotlinCompilation.ExitCode.OK, result.exitCode, "Compilation failed:\n${result.messages}")

        // AppUserBuilder should have both createdBy and updatedBy methods (not generic 'task')
        val appUserBuilderClass = result.classLoader.loadClass("$outputPackage.AppUserBuilder")
        val methodNames = appUserBuilderClass.methods.map { it.name }.toSet()
        assertTrue("createdBy" in methodNames, "AppUserBuilder should have createdBy() method — FK-column-based naming")
        assertTrue("updatedBy" in methodNames, "AppUserBuilder should have updatedBy() method — FK-column-based naming")
        assertTrue("task" !in methodNames, "AppUserBuilder should NOT have generic 'task' method")
    }

    // -----------------------------------------------------------------------
    // Test 8: Multi-FK inserts correct FK resolution via createdBy builder
    // -----------------------------------------------------------------------

    @Test
    fun multipleFkToSameTableInserts() {
        val result = compile(listOf(edgeCaseHarnessSource()))
        assertEquals(KotlinCompilation.ExitCode.OK, result.exitCode, "Compilation failed:\n${result.messages}")

        val ctx = freshContext()
        val harnessClass = result.classLoader.loadClass("$outputPackage.EdgeCaseHarness")
        val harnessInstance = harnessClass.getField("INSTANCE").get(null)
        val runMethod = harnessClass.getMethod("runMultiFk", DSLContext::class.java)
        runMethod.invoke(harnessInstance, ctx)

        // Verify task was inserted
        val taskCount = ctx.selectCount().from(DSL.table("task")).fetchOne(0, Int::class.java)!!
        assertEquals(1, taskCount, "Expected 1 task row")

        // Verify created_by is set to Alice's id
        val aliceId = ctx.select(DSL.field("id"))
            .from(DSL.table("app_user"))
            .where(DSL.field("name").eq("Alice"))
            .fetchOne()?.get(DSL.field("id"))
        assertNotNull(aliceId, "Alice should be in the DB")

        val taskCreatedBy = ctx.select(DSL.field("created_by"), DSL.field("updated_by"))
            .from(DSL.table("task"))
            .fetchOne()
        assertEquals(aliceId, taskCreatedBy?.get(DSL.field("created_by")), "task.created_by should equal Alice's id")
        assertNull(taskCreatedBy?.get(DSL.field("updated_by")), "task.updated_by should be NULL")
    }

    // -----------------------------------------------------------------------
    // Placeholder harness — tests placeholder capture, cross-tree, override, fan-out
    // -----------------------------------------------------------------------

    private fun placeholderHarnessSource(): SourceFile = SourceFile.kotlin(
        "PlaceholderHarness.kt",
        """
        package com.nickanderssohn.generated

        import com.nickanderssohn.declarativejooq.DslResult
        import com.nickanderssohn.declarativejooq.execute
        import org.jooq.DSLContext

        object PlaceholderHarness {

            /** PLCH-01 + PLCH-02: Capture placeholder, assign to FK property */
            fun runPlaceholderCapture(ctx: DSLContext): DslResult {
                return execute(ctx) {
                    organization {
                        name = "Acme"
                        val alice = appUser {
                            name = "Alice"
                            email = "alice@acme.com"
                        }
                        appUser {
                            name = "Bob"
                            email = "bob@acme.com"
                            createdBy {
                                title = "Bob Task by Alice"
                                createdBy = alice
                            }
                        }
                    }
                }
            }

            /** PLCH-03: Cross-tree — alice from tree 1 used in tree 2 */
            fun runCrossTree(ctx: DSLContext): DslResult {
                return execute(ctx) {
                    lateinit var alice: AppUserResult
                    organization {
                        name = "Acme"
                        alice = appUser {
                            name = "Alice"
                            email = "alice@acme.com"
                        }
                    }
                    organization {
                        name = "Beta"
                        appUser {
                            name = "Bob"
                            email = "bob@beta.com"
                            createdBy {
                                title = "Cross-tree task"
                                createdBy = alice
                            }
                        }
                    }
                }
            }

            /** PLCH-04: Placeholder overrides parent-context FK */
            fun runOverride(ctx: DSLContext): DslResult {
                return execute(ctx) {
                    val beta = organization { name = "Beta" }
                    organization {
                        name = "Acme"
                        appUser {
                            name = "Bob"
                            email = "bob@beta.com"
                            organization = beta
                        }
                    }
                }
            }

            /** Fan-out: one placeholder assigned to multiple tasks */
            fun runFanOut(ctx: DSLContext): DslResult {
                return execute(ctx) {
                    organization {
                        name = "Acme"
                        val alice = appUser {
                            name = "Alice"
                            email = "alice@acme.com"
                        }
                        appUser {
                            name = "Worker"
                            email = "worker@acme.com"
                            createdBy {
                                title = "Task 1"
                                createdBy = alice
                            }
                            createdBy {
                                title = "Task 2"
                                createdBy = alice
                            }
                        }
                    }
                }
            }
        }
        """.trimIndent()
    )

    // -----------------------------------------------------------------------
    // Test 9: Placeholder capture and FK assignment
    // -----------------------------------------------------------------------

    @Test
    fun placeholderCapture() {
        val result = compile(listOf(placeholderHarnessSource()))
        assertEquals(KotlinCompilation.ExitCode.OK, result.exitCode, "Compilation failed:\n${result.messages}")

        val ctx = freshContext()
        val harnessClass = result.classLoader.loadClass("$outputPackage.PlaceholderHarness")
        val harnessInstance = harnessClass.getField("INSTANCE").get(null)
        val runMethod = harnessClass.getMethod("runPlaceholderCapture", DSLContext::class.java)
        runMethod.invoke(harnessInstance, ctx)

        val aliceId = ctx.select(DSL.field("id")).from(DSL.table("app_user"))
            .where(DSL.field("name").eq("Alice")).fetchOne()?.get(DSL.field("id"))
        val taskCreatedBy = ctx.select(DSL.field("created_by")).from(DSL.table("task"))
            .fetchOne()?.get(DSL.field("created_by"))
        assertNotNull(aliceId, "Alice should be in the DB")
        assertEquals(aliceId, taskCreatedBy, "task.created_by should equal Alice's id via placeholder")
    }

    // -----------------------------------------------------------------------
    // Test 10: Cross-tree placeholder wiring
    // -----------------------------------------------------------------------

    @Test
    fun crossTreePlaceholder() {
        val result = compile(listOf(placeholderHarnessSource()))
        assertEquals(KotlinCompilation.ExitCode.OK, result.exitCode, "Compilation failed:\n${result.messages}")

        val ctx = freshContext()
        val harnessClass = result.classLoader.loadClass("$outputPackage.PlaceholderHarness")
        val harnessInstance = harnessClass.getField("INSTANCE").get(null)
        val runMethod = harnessClass.getMethod("runCrossTree", DSLContext::class.java)
        runMethod.invoke(harnessInstance, ctx)

        val aliceId = ctx.select(DSL.field("id")).from(DSL.table("app_user"))
            .where(DSL.field("name").eq("Alice")).fetchOne()?.get(DSL.field("id"))
        val taskCreatedBy = ctx.select(DSL.field("created_by")).from(DSL.table("task"))
            .fetchOne()?.get(DSL.field("created_by"))
        assertEquals(aliceId, taskCreatedBy, "Cross-tree: task.created_by should equal Alice's id")
    }

    // -----------------------------------------------------------------------
    // Test 11: Placeholder overrides parent-context FK
    // -----------------------------------------------------------------------

    @Test
    fun placeholderOverridesParentContext() {
        val result = compile(listOf(placeholderHarnessSource()))
        assertEquals(KotlinCompilation.ExitCode.OK, result.exitCode, "Compilation failed:\n${result.messages}")

        val ctx = freshContext()
        val harnessClass = result.classLoader.loadClass("$outputPackage.PlaceholderHarness")
        val harnessInstance = harnessClass.getField("INSTANCE").get(null)
        val runMethod = harnessClass.getMethod("runOverride", DSLContext::class.java)
        runMethod.invoke(harnessInstance, ctx)

        val betaId = ctx.select(DSL.field("id")).from(DSL.table("organization"))
            .where(DSL.field("name").eq("Beta")).fetchOne()?.get(DSL.field("id"))
        val bobOrgId = ctx.select(DSL.field("organization_id")).from(DSL.table("app_user"))
            .where(DSL.field("name").eq("Bob")).fetchOne()?.get(DSL.field("organization_id"))
        assertEquals(betaId, bobOrgId, "Bob's organization_id should be Beta (placeholder override)")
    }

    // -----------------------------------------------------------------------
    // Test 12: Fan-out — one placeholder used by multiple tasks
    // -----------------------------------------------------------------------

    @Test
    fun placeholderFanOut() {
        val result = compile(listOf(placeholderHarnessSource()))
        assertEquals(KotlinCompilation.ExitCode.OK, result.exitCode, "Compilation failed:\n${result.messages}")

        val ctx = freshContext()
        val harnessClass = result.classLoader.loadClass("$outputPackage.PlaceholderHarness")
        val harnessInstance = harnessClass.getField("INSTANCE").get(null)
        val runMethod = harnessClass.getMethod("runFanOut", DSLContext::class.java)
        runMethod.invoke(harnessInstance, ctx)

        val aliceId = ctx.select(DSL.field("id")).from(DSL.table("app_user"))
            .where(DSL.field("name").eq("Alice")).fetchOne()?.get(DSL.field("id"))
        val taskCreatedBys = ctx.select(DSL.field("created_by")).from(DSL.table("task"))
            .fetch().map { it.get(DSL.field("created_by")) }
        assertEquals(2, taskCreatedBys.size, "Expected 2 tasks")
        assertTrue(taskCreatedBys.all { it == aliceId }, "Both tasks should have created_by = Alice's id")
    }

    // -----------------------------------------------------------------------
    // Test 5: GeneratedDslResult has typed accessors
    // -----------------------------------------------------------------------

    @Test
    fun generatedDslResultHasTypedAccessors() {
        val result = compile(listOf(testHarnessSource()))
        assertEquals(KotlinCompilation.ExitCode.OK, result.exitCode, "Compilation failed:\n${result.messages}")

        val ctx = freshContext()
        val harnessClass = result.classLoader.loadClass("$outputPackage.TestHarness")
        val harnessInstance = harnessClass.getField("INSTANCE").get(null)
        val runMethod = harnessClass.getMethod("runWithTypedResult", DSLContext::class.java)
        val typedResult = runMethod.invoke(harnessInstance, ctx)

        assertNotNull(typedResult, "runWithTypedResult should return non-null")

        // Call organizations() accessor on GeneratedDslResult
        val orgsMethod = typedResult.javaClass.getMethod("organizations")
        @Suppress("UNCHECKED_CAST")
        val orgs = orgsMethod.invoke(typedResult) as List<*>
        assertTrue(orgs.isNotEmpty(), "organizations() should return non-empty list")

        // Get name property from OrganizationResult via reflection
        val orgResult = orgs[0]!!
        val nameGetter = orgResult.javaClass.getMethod("getName")
        val name = nameGetter.invoke(orgResult)
        assertEquals("Acme", name, "OrganizationResult.name should be 'Acme'")
    }
}
